<a href="https://colab.research.google.com/github/TheoNass/Exercice/blob/master/taskA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

Data Generation
===

In [2]:
num_samples, num_features = 10, 5

In [3]:
np.random.seed(10)
data = np.random.rand(num_samples, num_features)

Solution
===

In [4]:
print(data)

[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
 [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
 [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]
 [0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317]
 [0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
 [0.8052232  0.52164715 0.90864888 0.31923609 0.09045935]
 [0.30070006 0.11398436 0.82868133 0.04689632 0.62628715]
 [0.54758616 0.819287   0.19894754 0.8568503  0.35165264]
 [0.75464769 0.29596171 0.88393648 0.32551164 0.1650159 ]]


In [28]:
def standardize(x):
    output=np.array([])
    for n in np.nditer(x, op_flags = ['readonly']):
      output = np.append(output,[(n-x.mean())/x.std()])
    output = np.reshape(output, x.shape)
    return output

std_data = standardize(data)

In [29]:
print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[ 0.98315179 -1.7550482   0.48089984  0.90100688 -0.01211791]
 [-1.01065906 -1.10818836  0.94378832 -1.2138102  -1.50847638]
 [ 0.66955234  1.64738343 -1.81635085  0.03780817  1.13382225]
 [ 0.40384265  0.8023292  -0.76594212  1.51743855  0.77613706]
 [ 0.14853772 -1.3120947  -0.46874531  0.62859727 -0.21887354]
 [-0.24739922  0.42296237  0.04125926  0.5420028   0.36193574]
 [ 1.10683397  0.07230118  1.48414814 -0.66612819 -1.50074396]
 [-0.73375074 -1.41492079  1.19241315 -1.65966917  0.45404537]
 [ 0.166931    1.15814106 -1.10496092  1.29517828 -0.5478672 ]
 [ 0.92232608 -0.75103703  1.39399318 -0.64323394 -1.22874922]] 

 [ 0.24093665 -0.22381718  0.13805027  0.07391904 -0.22908878] 

 [0.68878128 1.13921042 1.08753597 1.02532553 0.89922459]
